### ISSUE TITLE
Provide the proxy client artifacts through the Maven Central and Spring's repo.spring.io

### ISSUE THREAD

**Issue by tzolov** [micrometer-metrics/prometheus-rsocket-proxy#2]
Currently all proxy client artifacts are available only in the [JCenter](https://jcenter.bintray.com/io/micrometer/publishing/) maven repository.  Even there the latest 0.7.0 version is missing.

For normal operation most of the Spring ecosystem projects expects the dependent artifacts in the following repositories:
 * releases - maven central: https://repo1.maven.org/maven2
 * snapshots - spring-snapshots: https://repo.spring.io/snapshot
 * milestones - spring-milestones: https://repo.spring.io/milestone

**Comment by shakuzen** [comment]
CI is now setup. Snapshots are now being published to the spring snapshot repository and releases are setup to be published to maven central going forward.

**Comment by tzolov** [comment]
I can see that the 0.8.0-SNAPSHOT is in  https://repo.spring.io/snapshot already :) Thanks

**Comment by tzolov** [comment]
This issue is resolved
