### ISSUE TITLE
Client throws java.nio.BufferUnderflowException for meter tasks that last more then 10 - 15 seconds

### ISSUE THREAD

**Issue by tzolov** [micrometer-metrics/prometheus-rsocket-proxy#3]
I've implemented a simple boot:
```
@SpringBootApplication
public class PrometheusRsocketDemoApplication implements CommandLineRunner {

	private Timer.Sample sample;

	public static void main(String[] args) {
		SpringApplication.run(PrometheusRsocketDemoApplication.class, args);
	}

	@Override
	public void run(String... args) throws Exception {

		this.sample = Timer.start(Metrics.globalRegistry);

		Thread.sleep(10 * 1000);

		System.out.println("Bingo");

		this.sample.stop(Timer.builder("net.tzolov.demo")
				.description("Task duration")
				.tag("my.simple.tag", "tag.tag")
				.register(Metrics.globalRegistry));
	}
}
```
with dependencies: 
```
	<properties>
		<java.version>1.8</java.version>
		<prometheus-rsocket-spring.version>0.6.2</prometheus-rsocket-spring.version>
		<micrometer.version>1.1.5</micrometer.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>io.micrometer.publishing</groupId>
			<artifactId>prometheus-rsocket-spring</artifactId>
			<version>${prometheus-rsocket-spring.version}</version>
		</dependency>
		<dependency>
			<groupId>io.micrometer.publishing</groupId>
			<artifactId>prometheus-rsocket-client</artifactId>
			<version>${prometheus-rsocket-spring.version}</version>
		</dependency>
		<dependency>
			<groupId>io.micrometer</groupId>
			<artifactId>micrometer-registry-prometheus</artifactId>
			<version>${micrometer.version}</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
		</dependency>
           .....
```
and application properties: 
```
management.metrics.export.prometheus.enabled=true
management.metrics.export.prometheus.rsocket.enabled=true

#localhost
management.metrics.export.prometheus.rsocket.host=localhost

management.metrics.export.prometheus.rsocket.port=7001

# default is Long.MAX_VALUE
management.metrics.export.prometheus.rsocket.max-retries=10000
management.metrics.export.prometheus.rsocket.first-backoff=10s
management.metrics.export.prometheus.rsocket.max-backoff=10m
```

Later triggers this exception: 
```
	at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:945) [spring-context-5.1.8.RELEASE.jar:5.1.8.RELEASE]
Caused by: java.nio.BufferUnderflowException: null
	at java.nio.DirectByteBuffer.get(DirectByteBuffer.java:271) ~[na:1.8.0_152]
	at io.micrometer.prometheus.rsocket.PrometheusRSocketClient.scrapePayload(PrometheusRSocketClient.java:119) [prometheus-rsocket-client-0.6.2.jar:0.6.2]
	... 29 common frames omitted
```

if i lower the wait period to 2-3 seconds i don't  see the exception. 

The error is still present with 0.8.0 client + proxy as well as with websocet transport

**Comment by jkschneider** [comment]
@tzolov Does this exception occur after application shutdown begins?

**Comment by smaldini** [comment]
I wonder if the key should be sliced before getting set in the lastBuffer or before getting consumed by scrapePayload. The exception seems to occur because the buffer is read more than once.

**Comment by tzolov** [comment]
@jkschneider , just checked and indeed the exception is thrown during the [pushOnDisconnect](https://github.com/micrometer-metrics/prometheus-rsocket-proxy/blob/master/client/src/main/java/io/micrometer/prometheus/rsocket/PrometheusRSocketClient.java#L87)

NOTE: Another important observation is that the issue manifests itself only when the [/metrics/proxy](https://github.com/micrometer-metrics/prometheus-rsocket-proxy/blob/master/proxy/src/main/java/io/micrometer/prometheus/rsocket/Main.java#L139) and [/metrics/connected](https://github.com/micrometer-metrics/prometheus-rsocket-proxy/blob/master/proxy/src/main/java/io/micrometer/prometheus/rsocket/Main.java#L144) entry points are pulled by Prometheus.  If i stop the prometheus from pulling the targets the exception is not thrown.
Could this be some sort of concurrency issue? 

My Prometheus target configuration looks like this: 
```
  - job_name: 'local-rsocket-proxy'

    scrape_interval: 10s
    scrape_timeout: 9s
    metrics_path: '/metrics/proxy'
    static_configs:
      - targets: ['172.20.10.4:9096']

  - job_name: 'local-rsocket-connected'

    scrape_interval: 10s
    scrape_timeout: 9s
    metrics_path: '/metrics/connected'
    static_configs:
      - targets: ['172.20.10.4:9096']
```

Maybe the 10s `scrape_interval` and the fact that the exception is thrown when the task last more then 10 secs are related.

**Comment by tzolov** [comment]
@smaldini ^^^ 
Could you elaborate on where exactly to call slice? I can give it a try.

**Comment by tzolov** [comment]
@jkschneider to add to my observation, the exception is thrown when the [rsocket#requestResponse()](https://github.com/micrometer-metrics/prometheus-rsocket-proxy/blob/master/client/src/main/java/io/micrometer/prometheus/rsocket/PrometheusRSocketClient.java#L51)  (prometheus initiated scrape i guess) is called at least once before the `pushOnDisconnect`

**Comment by shakuzen** [comment]
Thank you everyone for the details. I was able to reproduce this and I have a fix for it locally. Once I figure out how to write the unit test with RSocket stuff, I will get this taken care of.
