### ISSUE TITLE
Disable the Client autoconfiguration

### ISSUE THREAD

**Issue by MatonAnthony** [micrometer-metrics/prometheus-rsocket-proxy#34]
While using the Spring Boot starter in some situations (such as testing scenarios), it would be nice to be able to disable the autoconfiguration.

There is currently not properties to do this contrary to what you find in other metrics exporter such as the influx one.

Would a merge request for a feature like this be welcome?
Is there a way to do it currently?

**Comment by jkschneider** [comment]
@MatonAnthony You can set the `management.metrics.export.prometheus.rsocket=false` property in a profile.

**Comment by MatonAnthony** [comment]
Thanks a lot for your time.

The property `management.metrics.export.prometheus.rsocket.enabled` works with `false`, I didn't thought about looking at the annotation on the class :|
