### ISSUE TITLE
Is the project still maintained/reliable?

### ISSUE THREAD

**Issue by nightswimmings** [micrometer-metrics/prometheus-rsocket-proxy#43]
There seems not to be any activity almost for a year, not even on current issues. Is this because the project is stable, or just abandoned for some time or in favour of better alternatives ? (if so we would appreciate a note on the README)

**Comment by jonatan-ivanov** [comment]
Hi,

We haven't had any new issues for about a year so we haven't really changed it since then.
Please feel free to open issues/PRs if you want to propose changes.
