### ISSUE TITLE
log4j vulnerability

### ISSUE THREAD

**Issue by sergiupantiru** [micrometer-metrics/prometheus-rsocket-proxy#45]
Hello,
It looks like version 1.3.0 contains log4j vulnerability.
`prometheus-rsocket-proxy-1.3.0.jar/BOOT-INF/lib/log4j-api-2.13.3.jar`

Can we update with new log4j jar ?

**Comment by shakuzen** [comment]
We can update dependencies and release a new version, but note that the log4j-api jar is not vulnerable. See Log4j's [security page](https://logging.apache.org/log4j/2.x/security.html) with the following info:

> Note that only the log4j-core JAR file is impacted by this vulnerability. Applications using only the log4j-api JAR file without the log4j-core JAR file are not impacted by this vulnerability.

**Comment by sergiupantiru** [comment]
Just realized that log4j core is not part of it. Sorry for causing a confusion.
