### ISSUE TITLE
Upgrade to Spring Boot 3.1.1 and Java 17 baseline

### ISSUE THREAD

**Issue by shakuzen** [micrometer-metrics/prometheus-rsocket-proxy#62]

**Comment by klopfdreh** [comment]
Just a small question - can you release a version with Spring Boot 2.7.9 (1.5.x) before upgrading to Spring Boot 3.0.0 (1.6.0) as it requires Java 17 and we have only Java 11 available right now?

**Comment by shakuzen** [comment]
Sure, I think we can do that. Please open a separate issue for the upgrade to Boot 2.7.9.

**Comment by klopfdreh** [comment]
Thanks a lot! 👍

**Comment by klopfdreh** [comment]
Related Ticket: https://github.com/micrometer-metrics/prometheus-rsocket-proxy/issues/67

**Comment by kwangyong-park** [comment]
@shakuzen when will Spring Boot 3.0 support be available?

**Comment by shakuzen** [comment]
@kwangyong-park I've upgraded to Spring Boot 3.1.1 and it is now available in snapshots (`1.6.0-SNAPSHOT`). Would you be able to test it out for us and let us know if there are any issues with it?

**Comment by RomainWilbert** [comment]
Could you push the snapshot into maven repository ?

**Comment by shakuzen** [comment]
It should be in the Spring snapshot repo: https://repo.spring.io/snapshot

**Comment by RomainWilbert** [comment]
Seems that version 1.5.2 works with SB3 (3.1.0) & Java 17...

**Comment by jonatan-ivanov** [comment]
@RomainWilbert Could you please check again, `1.5.2` should use Boot `2.7.13` (see [prometheus-rsocket-proxy-1.5.2.pom](https://repo1.maven.org/maven2/io/micrometer/prometheus/prometheus-rsocket-proxy/1.5.2/prometheus-rsocket-proxy-1.5.2.pom)) while `1.6.0-SNAPSHOT` should use Boot `3.1.1` (see: [prometheus-rsocket-proxy-1.6.0-20230707.052345-13.pom](https://repo.spring.io/ui/native/snapshot/io/micrometer/prometheus/prometheus-rsocket-proxy/1.6.0-SNAPSHOT/prometheus-rsocket-proxy-1.6.0-20230707.052345-13.pom)).

**Comment by RomainWilbert** [comment]
Ok i got this, maybe i made myself not clear : i have tested version 1.5.2 with a Spring Boot 3 project and it works flawlessly (metrics are scraped by rsocket proxy server)
