### ISSUE TITLE
PrometheusRSocketClient's connection is timing out very often

### ISSUE THREAD

**Issue by klopfdreh** [micrometer-metrics/prometheus-rsocket-proxy#86]
Currently `PrometheusRSocketClient` is timing out very often when trying to connect to the proxy-server.

It would be great to make the Duration of `connectBlockingly(Duration timeout)` configurable.

This would also affect `prometheus-rsocket-spring` properties, so that you can add a specific property to your `application.yml`

See: https://github.com/micrometer-metrics/prometheus-rsocket-proxy/blob/main/client/src/main/java/io/micrometer/prometheus/rsocket/PrometheusRSocketClient.java#L304

This might also relate to `pushAndCloseBlockingly(Duration timeout);`

**Comment by shakuzen** [comment]
Sounds reasonable to me. Would you be willing to submit a pull request for this?

**Comment by klopfdreh** [comment]
Yes I can provide a PR. 😀

**Comment by klopfdreh** [comment]
> Sounds reasonable to me. Would you be willing to submit a pull request for this?

PR is provided. 👍
